export enum Matiere {
    Francais = 'Francais',
    Anglais = 'Anglais',
    Arabe = 'Arabe',
    Philosophie = 'Philosophie',
    Mathematiques = 'Mathematiques',
    Physique = 'Physique',
    Chimie = 'Chimie',
    Biologie = 'Biologie',
    Informatique = 'Informatique',
    Histoire = 'Histoire',
    Geographie = 'Géographie',
    Economie = 'Economie',
    Gestion = 'Gestion',
    Technologie = 'Technologie',
    Arts = 'Arts',
    Sport = 'Sport',
  }  